[package]
name = "client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy_ecs = "0.17"
bevy_remote = "0.17"
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
