[package]
name = "client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
bevy_remote = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
