pub const CAMERA: &str = "bevy_camera::camera::Camera";
pub const CHILD_OF: &str = "bevy_ecs::hierarchy::ChildOf";
pub const CHILDREN: &str = "bevy_ecs::hierarchy::Children";
pub const COMPUTED_NODE: &str = "bevy_ui::ui_node::ComputedNode";
pub const COMPUTED_TEXT_BLOCK: &str = "bevy_text::text::ComputedTextBlock";
pub const COMPUTED_UI_TARGET_CAMERA: &str = "bevy_ui::ui_node::ComputedUiTargetCamera";
pub const GLOBAL_TRANSFORM: &str = "bevy_transform::components::global_transform::GlobalTransform";
pub const LIGHT_CASCADES: &str = "bevy_light::cascade::Cascades";
pub const LIGHT_DIRECTIONAL: &str = "bevy_light::directional_light::DirectionalLight";
pub const LIGHT_POINT: &str = "bevy_light::point_light::PointLight";
pub const LIGHT_SPOT: &str = "bevy_light::spot_light::SpotLight";
pub const MESH_2D: &str = "bevy_mesh::components::Mesh2d";
pub const MESH_3D: &str = "bevy_mesh::components::Mesh3d";
pub const MONITOR: &str = "bevy_window::monitor::Monitor";
pub const NAME: &str = "bevy_ecs::name::Name";
pub const NODE: &str = "bevy_ui::ui_node::Node";
pub const OBSERVER_STATE: &str = "bevy_ecs::observer::runner::ObserverState"; // TODO: Replace with 0.17 equivalent
pub const POINTER_ID: &str = "bevy_picking::pointer::PointerId";
pub const POINTER_PRESS: &str = "bevy_picking::pointer::PointerPress";
pub const SYSTEM_ID_MARKER: &str = "bevy_ecs::system::system_registry::SystemIdMarker"; // TODO: Replace with 0.17 equivalent
pub const TEXT: &str = "bevy_ui::widget::text::Text";
pub const TEXT_LAYOUT_INFO: &str = "bevy_text::pipeline::TextLayoutInfo";
pub const WINDOW: &str = "bevy_window::window::Window";
