[application]

# App (Project) Name
name = "birp"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[bundle]
icon = ["app_dx/app-icon.png"]
identifier = "net.gutxi.birp"
publisher = "Gutxi"

[web.app]

# HTML title tag content
title = "BiRP"
# Base path for: https://doup.github.io/birp/
base_path = "birp"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
